name: Post Simple Values to Tandem

on:
  workflow_dispatch:

jobs:
  send_values:
    runs-on: ubuntu-latest
    steps:
      - name: Send Temperature (22.3)
        run: |
          curl -X POST "PASTE_TEMPERATURE_STREAM_URL_HERE" \
            -H "Content-Type: application/json" \
            --data-raw '{"Temperature": 22.3}'

      - name: Send Humidity (30)
        run: |
          curl -X POST "PASTE_HUMIDITY_STREAM_URL_HERE" \
            -H "Content-Type: application/json" \
            --data-raw '{"Humidity": 30}'
