name: Post Simple Values to Tandem

on:
  workflow_dispatch:

jobs:
  send_values:
    runs-on: ubuntu-latest
    steps:
      - name: Send Temperature (22.3)
        run: |
          curl -sS -o /dev/null -w "Temperature HTTP: %{http_code}\n" \
            -X POST "https://:uKY1jonlQzSQxqqbECXOjg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:nJH85NjvTGGcGaJ6R3tyVg/streams/AQAAADt6KahyMEh_uA4wNwtPYOsAAAAA" \
            -H "Content-Type: application/json" \
            --data-raw '{"value": 22.3}'

      - name: Send Humidity (30)
        run: |
          curl -sS -o /dev/null -w "Humidity HTTP: %{http_code}\n" \
            -X POST "https://:waSkr2APSj-UOv7ezjD4Cg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:nJH85NjvTGGcGaJ6R3tyVg/streams/AQAAAAhMwkjcdUPiu-T8R5T7QVMAAAAA" \
            -H "Content-Type: application/json" \
            --data-raw '{"value": 30}'
